#!/bin/bash

# Instalar herramientas para la línea de comandos
read -p "¿Instalar herramientas para la línea de comandos? [Y/N]: " c
if [[ $c =~ ^[Yy]$ ]]; then yay -S zsh zsh-syntax-highlighting wget curl tree sl rsync ntfs-3g man-pages man-db links mlocate lshw htop gnome-screenshot rkhunter ccat secure-delete; fi

# Instalar herramientas para el entrono gráfico
read -p "¿Instalar herramientas para el entorno gráfico? [Y/N]: " d
if [[ $d =~ ^[Yy]$ ]]; then yay -S xf86-video-vesa xorg-server xorg-xinit noto-fonts ttf-ubuntu-font-family; fi
cp /etc/X11/xinit/xinitrc ~/.xinitrc
read -p "¿Intalar drivers y herramientas de nvidia? [Y/N]: " e
if [[ $e =~ ^[Yy]$ ]]; then yay -S nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader; fi

# Instalar entorno de escritorio bspwm
read -p "¿Instalar bspwm y herramientas de ayuda? [Y/N]: " f
if [[ $f =~ ^[Yy]$ ]]; then yay -S bspwm sxhkd xorg-xinput xdo xdotool feh dunst kitty dmenu polybar polybar-spotify-git cherry-font-git siji-git; fi

# Instalar herramientas con GUI
read -p "¿Instalar herramientas con GUI? [Y/N]: " g
if [[ $g =~ ^[Yy]$ ]]; then yay -S vlc mumble gedit notepadqq nemo spotify firefox libreoffice-fresh libreoffice-fresh-es kolourpaint ksysguard gnome-calculator kitty drawio-desktop ttf-envy-code-r p7zip-gui; fi
