#!/bin/bash


# Ordenar mirrors 
read -p "¿Ordenar mirrors? [Y/N]: " mir
if [[ $mir =~ ^[Yy]$ ]]; then 
	curl -o /etc/pacman.d/mirrorlist https://www.archlinux.org/mirrorlist/all/
	sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
	awk '/^## Spain$/{f=1; next}f==0{next}/^$/{exit}{print substr($0, 1);}' /etc/pacman.d/mirrorlist.backup | sed 's/^#Server/Server/' | rankmirrors -n 4 - | sudo tee /etc/pacman.d/mirrorlist
	awk '/^## Worldwide$/{f=1; next}f==0{next}/^$/{exit}{print substr($0, 1);}' /etc/pacman.d/mirrorlist.backup | sed 's/^#Server/Server/' | rankmirrors -n 4 - | sudo tee -a /etc/pacman.d/mirrorlist
fi
	
# Instalar YAY
clear; echo "Instalando yay en" $(pwd)
git clone https://aur.archlinux.org/yay.git
cd yay; makepkg -sirc
cd ..; rm -dr yay
	

# Instalar herramientas para la línea de comandos
read -p "¿Instalar herramientas para la línea de comandos? [Y/N]: " a
[[ $a =~ ^[Yy]$ ]] && yay -S zsh zsh-syntax-highlighting wget curl tree sl rsync ntfs-3g man-pages man-db links mlocate lshw htop gnome-screenshot rkhunter ccat secure-delete

# Instalar herramientas para el entrono gráfico
read -p "¿Instalar herramientas para el entorno gráfico? [Y/N]: " b
[[ $b =~ ^[Yy]$ ]] && yay -S xf86-video-vesa xorg-server xorg-xinit noto-fonts ttf-ubuntu-font-family

read -p "¿Instalar drivers y herramientas de nvidia? [Y/N]: " c
[[ $c =~ ^[Yy]$ ]] && yay -S nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader

# Instalar entorno de escritorio bspwm
read -p "¿Instalar bspwm y herramientas de ayuda? [Y/N]: " d
[[ $d =~ ^[Yy]$ ]] && yay -S bspwm sxhkd xorg-xinput xdo xdotool feh dunst kitty dmenu polybar polybar-spotify-git cherry-font-git siji-git

# Instalar herramientas con GUI
read -p "¿Instalar herramientas con GUI? [Y/N]: " e
[[ $e =~ ^[Yy]$ ]] && yay -S vlc mumble gedit notepadqq nemo spotify firefox libreoffice-fresh libreoffice-fresh-es kolourpaint ksysguard gnome-calculator kitty drawio-desktop ttf-envy-code-r p7zip-gui


# Acciones extra
#activar firewall
cp /etc/X11/xinit/xinitrc ~/.xinitrc
chsh -s /bin/zsh
sl