#!/bin/bash

# --- Sript personalizado para automatizar la configuración de Arch. ---

# Comprobar si estás logeado como root
if [ $(whoami) != "root" ]; then echo "No estás logeado como root"; exit; fi 

# Usuarios y contraseñas
echo "Contraseña de root"; passwd
echo acmpc > /etc/hostname
useradd -m -G wheel alberto
echo "Contraseña de usuario"; passwd alberto
sed -i ':a;N;$!ba;s/## Uncomment to allow members of group wheel to execute any command\n# %wheel ALL=(ALL) ALL/## Uncomment to allow members of group wheel to execute any command\n%wheel ALL=(ALL) ALL(ALL) ALL/g' /etc/sudoers #Se puede simplifocar poniendo simplemente la línea donde quiero la sustitución / también ha fallado

# Hora e idioma
ln -sf /usr/share/zoneinfo/Madrid/Europe /etc/localtime
hwclock --systohc
echo LANG=es_ES.UTF-8 > /etc/locale.conf
echo KEYMAP=es > /etc/vconsole.conf
sed -i 's/#es_ES[.]UTF-8 UTF-8/es_ES.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

# Conexión
ip link
read -p "Escribe el dispositivo de red que quieras usar: " dis; dis=$dis".service"
systemctl enable dhcpcd@$dis; systemctl start dhcpcd@$dis
ping -c 3 archlinux.org; read -p "¿Problemas de conexión? [Y/N]: " b
if [[ $b =~ ^[Yy]$ ]]; then echo "Revisa que todo esté bien y posiblemente tengas que rehacer la instalación"; exit 1; fi
sed -i ':a;N;$!ba;s/# Misc options\n#UseSyslog\n#Color/# Misc options\n#UseSyslog\nColor/g' /etc/pacman.conf 
sed -i ':a;N;$!ba;s/#\[multilib\]\n#Include = \/etc\/pacman.d\/mirrorlist/[multilib]\nInclude = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf
pacman -Syy

# Instalar YAY
git clone https://aur.archlinux.org/yay.git
cd yay; makepkg -sirc
cd ..; rm -dr yay

# Instalar herramientas para la línea de comandos
read -p "¿Intalar herramientas para la línea de comandos? [Y/N]: " c
if [[ $c =~ ^[Yy]$ ]]; then yay -S zsh zsh-syntax-highlighting wget curl tree sl rsync ntfs-3g man-pages man-db links mlocate lshw htop gnome-screenshot rkhunter ccat secure-delete; fi

# Instalar herramientas para el entrono gráfico
read -p "¿Intalar herramientas para el entorno gráfico? [Y/N]: " d
if [[ $d =~ ^[Yy]$ ]]; then yay -S xf86-video-vesa xorg-server xorg-xinit noto-fonts ttf-ubuntu-font-family; fi
read -p "¿Intalar drivers y herramientas de nvidia? [Y/N]: " e
if [[ $e =~ ^[Yy]$ ]]; then yay -S nvidia-dkms nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader; fi

# Instalar entorno de escritorio bspwm
read -p "¿Intalar bspwm y herramientas de ayuda? [Y/N]: " f
if [[ $f =~ ^[Yy]$ ]]; then yay -S bspwm sxhkd xorg-xinput xdo xdotool feh dunst kitty dmenu polybar polybar-spotify-git cherry-font-git siji-git; fi

# Instalar herramientas con GUI
read -p "¿Intalar herramientas con GUI? [Y/N]: " g
if [[ $g =~ ^[Yy]$ ]]; then yay -S vlc mumble gedit notepadqq nemo spotify firefox libreoffice-fresh libreoffice-fresh-es kolourpaint ksysguard gnome-calculator kitty drawio-desktop ttf-envy-code-r p7zip-gui; fi





echo "configuración completa"
sl

