#!/bin/bash

# --- Sript personalizado para automatizar la configuración de Arch. ---

# Comprobar si estás logeado como root
if [ $(whoami) != "root" ]; then echo "No estás logeado como root"; exit; fi; clear

# Usuarios y contraseñas
echo "Contraseña de root"; passwd
echo acmpc > /etc/hostname
useradd -m -G wheel alberto
echo "Contraseña de usuario"; passwd alberto
EDITOR="nano +82" visudo

# Hora e idioma
ln -sf /usr/share/zoneinfo/Madrid/Europe /etc/localtime
hwclock --systohc
echo LANG=es_ES.UTF-8 > /etc/locale.conf
echo KEYMAP=es > /etc/vconsole.conf
sed -i 's/#es_ES[.]UTF-8 UTF-8/es_ES.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen

# Conexión
clear; ip link; echo "\n"

read -p "Escribe el número del dispositivo que quieras usar (EJ: 1, 2, 4...): " dis
systemctl enable dhcpcd@$(ip link | grep $dis: | awk '{print $2}' | sed 's/://g'); systemctl start dhcpcd@$(ip link | grep $dis: | awk '{print $2}' | sed 's/://g')

ping -c 3 archlinux.org; echo " "; read -p "¿Problemas de conexión? [Y/N]: " b
if [[ $b =~ ^[Yy]$ ]]; then echo "Revisa que todo esté bien y posiblemente tengas que rehacer la instalación"; exit 1; fi
sed -i ':a;N;$!ba;s/# Misc options\n#UseSyslog\n#Color/# Misc options\n#UseSyslog\nColor/g' /etc/pacman.conf 
sed -i ':a;N;$!ba;s/#\[multilib\]\n#Include = \/etc\/pacman.d\/mirrorlist/[multilib]\nInclude = \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf
pacman -Syy

echo "configuración completa"

