#! /bin/sh



# +---------------------+
# | PROGRAMAS DE INICIO |
# +---------------------+
killall -q sxhkd &
sxhkd -c ~/.config/sxhkd/sxhkdrc  &
# Wallpaper: feh --bg-scale ~/.themes/creamywall.png &
setxkbmap -layout es &
killall -q polybar &
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
polybar -c ~/.polybar/statusbar "simple" &
xinput --set-prop 14 'libinput Accel Profile Enabled' 0, 1 &
xinput --set-prop 14 'libinput Accel Speed' -.4 &
 




# +---------------------+
# |      MONITORES      |
# +---------------------+
bspc monitor DVI-D-0 -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X




# +---------------------+
# |        BORDES       |
# +---------------------+
bspc config border_width                  4
bspc config window_gap                    7
bspc config top_padding                   20 #Tamaño de polybar [CAMBIAR]
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0



# +--------------------------------+
# | COMPORTAMIENTO DE LAS VENTANAS |
# +--------------------------------+
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




# +---------------------+
# |        BORDES       |
# +---------------------+
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"




# +---------------------+
# |       POLYBAR       | #Desaparece cuando se maximiza la pantala
# +---------------------+
xdo below -t $(xdotool search --classname polybar)



# +---------------------+
# |        ??????       |
# +---------------------+
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
