#!/bin/bash

# LISTA DE ARCHIVOS QUE SIGO
# - Este (sincronizar-dotfiles)
# - configurador_automático_arch
# - Xresources
# - zshrc
# - kitty.conf
# - polybar

echo "+----------------------+
|  1 · Sincronizar     |
|  2 · Subir a GITHUB  |
|  3 · Exportar al PC  |
+----------------------+"
read -p "Escoge: " dec 

cd $(dirname $(realpath $0))

if [ $dec -eq 1 ]; then
		sudo rsync -aAXv --delete ~/.Xresources ~/.zshrc ~/.config/kitty/kitty.conf ~/.polybar ~/.config/bspwm/bspwmrc ~/.config/sxhkd/sxhkdrc . 
elif [ $dec -eq 2 ]; then
		git add $(realpath $0) configurador_automático_arch.sh .Xresources .zshrc kitty.conf .polybar bspwmrc sxhkdrc
		read -p "Commit? [Y/N]: " a; if [[ $a =~ ^[Yy]$ ]]; then git commit -m "Actualización automática"; fi
		read -p "Push? [Y/N]: " b; if [[ $b =~ ^[Yy]$ ]]; then git push origin master; fi
elif [ $dec -eq 3 ]; then
		cp .Xresources ~/
		cp .zshrc ~/
		mkdir ~/.config
		mkdir ~/.config/kitty
		cp kitty.conf ~/.config/kitty
		cp .polybar ~/
		mkdir ~/.config/bspwm
		cp bspwmrc ~/.config/bspwm
		mkdir ~/.config/sxhkd
		cp sxhkdrc ~/.config/sxhkd
else echo "You had one job." ; fi