#!/bin/bash

# Este script ha de mantenerse en el directorio de git donde se requieren los dotfiles, de lo contrario cd $(dirname $(realpath $0)) fallará.
# Este script tiene rsync, git, coreutils, sudo y bash como dependencias


# Las rutas a los dotfiles han de especificarse en el array DOTFILES
declare -a DOTFILES=("$HOME/.Xresources" "$HOME/.zshrc" "$HOME/.config/kitty" "$HOME/.config/polybar" "$HOME/.config/bspwm" "$HOME/.config/sxhkd" "$HOME/.nanorc" "$HOME/.config/micro" "$HOME/.config/lemonbar" "$HOME/.mozilla/firefox/ojt8tp6c.default-release/chrome")
#--------------------------------------------------------------------------------------------



cd "$(dirname "$(realpath "$0")")" || exit
dec=$* # TODO: Esto tengo que modificarlo para no necesitar declarar una variable


if [ -z "$dec" ]; then
	echo "\
	+--------------------------------+
	|       S · Sincronizar          |
	|       G · Subir a GITHUB       |
	|       E · Exportar al PC       |
	|                                |
	|  Cualquier otra tecla · Salir  |
	+--------------------------------+"
	read -rp "Escoge: " dec
	dec=$(echo "-$dec")
fi

case $dec in # TODO: Encontrar la manera de que acepte atributos compinados como "-SG"
-s|-S)
	sudo rsync -aAXv --delete "${DOTFILES[@]}" .
	echo " "; ls -hNA --color=auto --group-directories-first; echo " "; git status; echo " "
	;;
-g|-G)
	git add --all ; git status; echo " "
	read -rp "Commit? [Y/N]: " a; [[ $a =~ ^[Yy]$ ]] && git commit -m "$(date)"
	read -rp "Push? [Y/N]: " b; [[ $b =~ ^[Yy]$ ]] && git push origin master
		;;
-e|-E)
	[ -d "$HOME/.config" ] || mkdir ~/.config # TODO: Encontrar la manera de que las carpetas contenedoras se autogeneren por muchas que sean
	for i in "${DOTFILES[@]}"; do
		sudo rsync -aAXv --delete "$(basename "$i")" "$(dirname "$i")"
	done
	;;
*)
	echo "	Argumentos:
	-s · Sincronizar
	-g · Subir a GITHUB
	-e · Exportar al PC"
	;;
esac