#!/bin/bash



# +---------------------+
# | PROGRAMAS DE INICIO |
# +---------------------+
feh --bg-scale ~/.themes/creamywall.png &
setxkbmap -layout es &

killall -q sxhkd polybar dunst polkit-gnome-authentication-agent-1

while pgrep -u $UID -x sxhkd >/dev/null; do sleep 1; done 
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
while pgrep -u $UID -x dunst >/dev/null; do sleep 1; done
while pgrep -u $UID -x polkit-gnome-authentication-agent-1 >/dev/null; do sleep 1; done
 
dunst &
polybar -c ~/.config/polybar/config/.statusbar "simple" &
sxhkd &
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &



# +---------------------+
# |      MONITORES      |
# +---------------------+
i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor \
        -n "$i" \
        -d {I,II,III,IV,V,VI,VII,VIII,IX,X}
    let i++
done
unset i




# +---------------------+
# |        BORDES       |
# +---------------------+
bspc config border_width                  4
bspc config window_gap                    7
bspc config top_padding                   20 #Tamaño de polybar + gap
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0



# +--------------------------------+
# | COMPORTAMIENTO DE LAS VENTANAS |
# +--------------------------------+
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_follows_pointer         false
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner




# +---------------------+
# |        BORDES       |
# +---------------------+
bspc config normal_border_color		      "#3a4560"
bspc config active_border_color	          "#3a4560"
bspc config focused_border_color	      "#a02a32"
bspc config presel_feedback_color	      "#5e81ac"




# +---------------------+
# |       POLYBAR       | #Desaparece cuando se maximiza la pantala
# +---------------------+
xdo above -t $(xdo id -n root) $(xdo id -n polybar)



# +---------------------+
# |        ??????       |
# +---------------------+
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
