#!/usr/bin/bash

#   //////////////
# --- COMUNES ---
# //////////////

hora() {
	date '+%H:%M'
}

fecha() {
	date '+%d-%m-%Y'
}

volumen() {
	amixer get Master | sed -n 's/^.*\[\([0-9]\+\)%.*$/\1/p'| uniq
}

volumen_mute() {
	amixer get Master | sed -n 's/^.*\[\(on\|off\).*$/\1/p' | uniq
}

usuario() {
    echo $USER@$(hostname)
}

conex() {
    echo "?"
}

2oplano() {
    echo "?"
}

notificaciones() {
    echo "?"
}

batería() {
    echo "?"
}




#   //////////////
# --- HARDWARE ---
# //////////////

INTELuso() {
	grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print substr(usage,0,2)}'
}

INTELtemp() {
	sensors | grep Package | awk '{print substr($4, 2, 2)}'
}

NVIDIAuso() {
	nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits
}

NVIDIAtemp() {
	nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits
}

RAMuso() {
	#free | grep Mem | awk '{print $3*100/$2}'
	free | grep Mem | awk '{print substr($3*100/$2,0,2)}'
}





#   ////////////////
# --- COMPLEJOS ---
# ////////////////

spotify() {
	echo "?"
}

escritorios() {
    echo "?"
}













